---
- name: install httpd + firewall opening
  gather_facts: no
  hosts: all
  tasks:
    - name: install firewalld
      yum:
        name: firewalld
        state: present
    - name: start firewalld
      service:
        name: firewalld
        state: started
    - name: start firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: create file
      copy:
        content: hello ansible
        dest: /var/www/html/index.html
