---
- name: lab3
  hosts: all
  vars:
    remote_dir : /etc/ansible/facts.d
    facts_file : localfacts.fact
  tasks:

    - name: create file
      file:
        path: ./storage.txt
        state: touch
      delegate_to: localhost

    - name: debug module
      debug:
        var: ansible_facts.hostname 
      register: debug_output

    - name: create file with content
      lineinfile: 
        path: ./storage.txt
        line: "{{debug_output}}"
        insertbefore: BOF
      delegate_to: localhost

    - name: create facts.d directory
      file:
        state: directory
        recurse: yes
        path : "{{remote_dir}}"

    - name: install custom facts
      copy:
        src: "{{facts_file}}"
        dest: "{{remote_dir}}"
      
